title: "Luis Castellanos"
author: "Luis Castellanos"
description: "My Personal Website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "aboutme.md", title: "About me"}
  - {file: "cv.md", title: "CV"}
  - {file: "notes.md", title: "My Notes"}
  - {file: "projects.md", title: "My Projects"}
  - {url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ", title: "Cool Stuff"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:luiscastelds@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/luiscastelds"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/luis-castellanos-145767380/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
